config/routes.rb
Rails.application.routes.draw do
  resources :enrollments do 
    get :my_students, on: :collection
  end
  devise_for :users
  resources :users
  resources :courses do
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    #I believe member here stands for current course
    #The member do lets me nest things within the show action. - How do I know its specifically show? What made it show.
    member do
      #This will add two new accounts in our routes.
      get :analytics
      patch :approve
      patch :unapprove
    end
    #Enrollments is above too, but im basically subclassing routes for enrollments methods new + create
    #beneath courses, so enrollments_new_path becomes courses_enrollments_new_path (a fictious example)
      resources :enrollments, only: [:new, :create]
      resources :lessons

  end
  root'home#index'
  get 'activity', to: 'home#activity'
  get 'analytics', to: 'home#analytics'

  namespace :charts do     
    get 'money_makers'
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'popular_courses'
  end
  #Compare above and below, since it seems to auto direct to the right method immediately.
  #get 'charts/users_per_day', to: 'charts#users_per_day'
  #get 'charts/enrollments_per_day', to: 'charts#enrollments_per_day'
  #get 'charts/popular_courses', to: 'charts#popular_courses'
  #get 'charts/money_makers', to: 'charts#money_makers'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.haml
%hr
%footer
  .container
    .row
      .col-md-4
        Copyright
        © 
        = Time.now.year
        CoursePlatform Sp. z o.o.
        .row
        .fa.fa-envelope
        = mail_to 'yashm@outlook.com'
        .row
      .col-md-4
        Privacy policy
        .row
        Terms and conditions
      .col-md-4
        About us
        .row
        = link_to 'Teach on CoursePlatform', new_course_path
%br 

app/views/shared/_messages.html.haml
%br/
.container
  - flash.each do |name, msg|
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'} alert-dismissible fade show", :role => "alert"}
      = msg
      %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => "true"} ×

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  %a.navbar-brand{:href => root_path} CourseGo
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    - if current_user
      %ul.navbar-nav.mr-auto
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(root_path)}"}
          = link_to root_path, class: 'nav-link' do
            .fa.fa-home
            Home
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(courses_path)}"}
          = link_to courses_path, class: 'nav-link' do
            .fa.fa-graduation-cap
            Courses
        .form-inline
          = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
            .input-group
              = f.search_field :title_cont, class: 'form-control-sm', style: 'float: left; width: 150px; ', placeholder: 'Find a course', :autocomplete => :off
              %span.input-group-append
                %button.btn.btn-primary.btn-sm{:type => "submit"}
                  %span.fa.fa-search{"aria-hidden" => "true"}
      %ul.navbar-nav.mr-auto
        - if current_user.has_role?(:student)
          %li.nav-item.dropdown
            %a#studentDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              .fa.fa-graduation-cap
              Learn 
            .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "studentDropdown"}
              = link_to purchased_courses_path, class: 'dropdown-item' do
                .fa.fa-graduation-cap
                Purchased Courses
                .badge.badge-danger
                  = current_user.enrollments_count
              = link_to pending_review_courses_path, class: 'dropdown-item' do
                .fa.fa-graduation-cap
                Pending Review
                .badge.badge-danger
                  =current_user.enrollments.pending_review.count
        - if current_user.has_role?(:teacher)
          %li.nav-item.dropdown
            %a#teacherDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              Teach
              .fa.fa-chalkboard-teacher
            .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "teacherDropdown"}
              = link_to new_course_path, class: 'dropdown-item' do
                .fa.fa-graduation-cap
                .fa.fa-plus
                New Course
              = link_to created_courses_path, class: 'dropdown-item' do
                .fa.fa-graduation-cap
                My Courses
                .badge.badge-danger
                  = current_user.courses_count
              = link_to my_students_enrollments_path, class: 'dropdown-item' do
                .fa.fa-users
                My Students
                .badge.badge-danger
                  = Enrollment.joins(:course).where(courses: {user: current_user}).count
        - if current_user.has_role?(:admin)
          %li.nav-item.dropdown
            %a#adminDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              Admin 
              .fa.fa-cog
            .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "adminDropdown"}
              = link_to users_path, class: "dropdown-item" do
                .fa.fa-user
                %b Users
                .badge.badge-danger
                  = User.count
              = link_to enrollments_path, class: 'dropdown-item' do
                .fa.fa-lock-open
                %b Enrollments
                .badge.badge-danger
                  = Enrollment.count
              = link_to analytics_path, class: 'dropdown-item' do
                .fa.fa-chart-pie
                %b Analytics
              = link_to activity_path, class: 'dropdown-item' do
                .fa.fa-signal
                %b Activity
              = link_to unapproved_courses_path, class: 'dropdown-item' do
                .fa.fa-signal
                %b Unapproved Courses
                .badge.badge-danger
                  = Course.unapproved.count
      /SEARCH IN NAVBAR

      /.form-inline.my-2.my-lg-0
      /  = form_tag(courses_path, method: :get) do
      /    .input-group
      /      = text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Find a course", class: 'form-control-sm'
      /      %span.input-group-append
      /        %button.btn.btn-primary.btn-sm{:type => "submit"}
      /          %span.fa.fa-search{"aria-hidden" => "true"}
      %ul.navbar-nav.mr-right
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            %b= current_user.email
          .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdown"}
            = link_to edit_user_registration_path, class: "dropdown-item" do
              .fa.fa-cog
              %b Account settings
            = link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do
              .fa.fa-sign-out-alt
              %b Sign out
    - else
      %ul.navbar-nav
        %li.nav-item= link_to 'Sign Up', new_user_registration_path, class: 'nav-link'
        %li.nav-item= link_to 'Log In', new_user_session_path, class: 'nav-link'