config/routes.rb
Rails.application.routes.draw do
  resources :enrollments do 
    get :my_students, on: :collection
  end
  devise_for :users
  resources :users
  resources :courses do
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    #I believe member here stands for current course
    #The member do lets me nest things within the show action. - How do I know its specifically show? What made it show.
    member do
      #This will add two new accounts in our routes.
      get :analytics
      patch :approve
      patch :unapprove
    end
    #Enrollments is above too, but im basically subclassing routes for enrollments methods new + create
    #beneath courses, so enrollments_new_path becomes courses_enrollments_new_path (a fictious example)
      resources :enrollments, only: [:new, :create]
      resources :lessons

  end
  root'home#index'
  get 'activity', to: 'home#activity'
  get 'analytics', to: 'home#analytics'

  namespace :charts do     
    get 'money_makers'
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'popular_courses'
  end
  #Compare above and below, since it seems to auto direct to the right method immediately.
  #get 'charts/users_per_day', to: 'charts#users_per_day'
  #get 'charts/enrollments_per_day', to: 'charts#enrollments_per_day'
  #get 'charts/popular_courses', to: 'charts#popular_courses'
  #get 'charts/money_makers', to: 'charts#money_makers'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]
  def index
    #Does this need to be scoped? Probably.
    @courses = Course.all_courses
    #This confuses me, the created_at: : desc => Descending Order!
    @latest_courses = Course.latest_courses.published.approved
    #@continue_courses = Course.limit(3).order(created_at: :desc).joins(:enrollments).where(enrollments: {user: current_user}).ransack(params[:courses_search], search_key: :courses_search)
    #I need to better understand the use of these ':' - Far too often I forgot them at random, but place them without understanding
    # Below is an example of two scopes, as initially in Enrollments I included a scope, in another scope. Which is bad practice.
    @latest_reviews = Enrollment.reviewed.latest_reviews

    @top_rated_courses = Course.top_rated_courses.published.approved
    @popular_courses = Course.popular_courses.published.approved
    #The lack of the ransack (see continue courses) makes sense - I'm not PASSING anything, and there are no params. Simply put
    #I only need to join the tables, use current_user, and you've located all courses in question.
    @purchased_courses = Course.purchased_courses(current_user)
  end

  def activity
    if current_user.has_role?(:admin)
      @pagy, @activity = pagy(PublicActivity::Activity.all.order(created_at: :desc), items: 10)
    else
      redirect_to root_path, alert: "You require admin rights for that."
    end

  end


  def analytics
    if current_user.has_role?(:admin)
      #@users = User.all
      #@enrollments = Enrollment.all
      #Most popular courses 
      #@courses = Course.all
      #@popular_courses = Course.where('enrollments_count > 0')
    else
      redirect_to root_path, alert: "You require admin rights for that." 
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/activity.html.haml
- content_for :title do 
	Coursego
	\|
	Current Activity



%h3
	Activity
	.badge.badge-info
		=@activity.count

%p

%ul.list-group
	- @activity.each do |activity|
		%li.list-group-item
			=activity.created_at.strftime('%d-%m-%Y %H:%m')
			(#{time_ago_in_words(activity.created_at)})
			=model_label(activity.trackable_type)
			/=activity.trackable_type
			-if activity.trackable_type == "Lesson"
				-if Lesson.where(id: activity.trackable_id).present?
					=link_to activity.trackable, course_lesson_path(activity.trackable.course, activity.trackable)
				-else
					Lesson was deleted
			-else
				=link_to activity.trackable, activity.trackable
			=activity.key
			=crud_label(activity.key.match(/\.(.*)/)[1])

			/=activity.owner
			=link_to activity.owner, user_path(activity.owner)
			- if activity.parameters.any?
				=activity.parameters


%p
!= pagy_bootstrap_nav(@pagy)
%br

app/views/home/analytics.html.haml
%h3.text-center
	Users Created
/Old Style - inefficient
/= line_chart @users.group_by_hour(:created_at).count
/New Style - efficient at large scale
= line_chart charts_users_per_day_path
%p

%h3.text-center
	Enrollments Created
= column_chart charts_enrollments_per_day_path
%p

%h3.text-center
	Course Popularity
/= pie_chart @courses.group(:enrollments_count).count
/In the below code, we group by and then pass well, I don't quite know why the '' - It ensures the second part is treated
/as a symbol as well. Further research required
= pie_chart charts_popular_courses_path

%p

%h3.text-center
	Money Makers
= column_chart charts_money_makers_path

app/views/home/index.html.haml
- content_for :title do 
	Coursego
	\|
	Online Courses - Learn Anything On Your Schedule



-# Comment Test - Note the below shows a nested under H1. H1 will be applied to both of these, based on the indentation.
-# I will need to be very careful, then, with my indents
.jumbotron
	.display-4
		What do you want to learn today?

	.p-4

	- if current_user
		= search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
			.input-group
				= f.search_field :title_cont, class: 'form-control-sm', style: 'float: left; width: 150px; ', placeholder: 'Find a course', :autocomplete => :off
				%span.input-group-append
					%button.btn.btn-primary.btn-sm{:type => "submit"}
						%span.fa.fa-search{"aria-hidden" => "true"}


.card-group
	.card.card-body
		%h1
			.fa.fa-graduation-cap
		= Course.count
		online courses
		.row
		Explore a variety of fresh topics
	.card.card-body
		%h1
			.fa.fa-chalkboard-teacher
			/.fa.fa-brain
		= Course.distinct.count(:user_id)
		expert instructors
		.row
		Find the right instructor for you
	.card.card-body
		%h1
			.fa.fa-user-graduate
		= User.count
		active learners
		.row
		Join the knowledge sharing community
	.card.card-body
		%h1
			.fa.fa-infinity
		Lifetime access
		.row
		Learn on your schedule




- if current_user	
	%hr
	%h2
		.fa.fa-user-graduate
		Contine Learning
	.card-columns
		- @purchased_courses.each do |course|
			= render 'courses/course', course: course
.text-right
	= link_to 'Purchased Courses', purchased_courses_path

%hr
%h2
	.fa.fa-chart-line
	Popular Courses
.card-columns
	- @popular_courses.each do |course|
		= render 'courses/course', course: course
.text-right
	=link_to 'Most Popular Courses', courses_path(courses_search: {s: 'enrollments_count desc'})
%hr
%h2
	.fa.fa-star
	Top Rated Courses
.card-columns
	- @top_rated_courses.each do |course|
		= render 'courses/course', course: course
.text-right
	=link_to 'Top Rated Courses', courses_path(courses_search: {s: 'average_rating desc'})
%hr
%h2
	.fa.fa-clock
	Most Recent Courses
.card-columns
	- @latest_courses.each do |course|
		= render 'courses/course', course: course
.text-right
	=link_to 'Top Rated Courses', courses_path(courses_search: {s: 'created_at desc'})

%hr
%h2
	Students Talk
	.fa.fa-clock
.card-columns
	- @latest_reviews.each do |enrollment|
		= render 'enrollments/enrollment', enrollment: enrollment