config/routes.rb
Rails.application.routes.draw do
  resources :enrollments do 
    get :my_students, on: :collection
  end
  devise_for :users
  resources :users
  resources :courses do
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    #I believe member here stands for current course
    #The member do lets me nest things within the show action. - How do I know its specifically show? What made it show.
    member do
      #This will add two new accounts in our routes.
      get :analytics
      patch :approve
      patch :unapprove
    end
    #Enrollments is above too, but im basically subclassing routes for enrollments methods new + create
    #beneath courses, so enrollments_new_path becomes courses_enrollments_new_path (a fictious example)
      resources :enrollments, only: [:new, :create]
      resources :lessons

  end
  root'home#index'
  get 'activity', to: 'home#activity'
  get 'analytics', to: 'home#analytics'

  namespace :charts do     
    get 'money_makers'
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'popular_courses'
  end
  #Compare above and below, since it seems to auto direct to the right method immediately.
  #get 'charts/users_per_day', to: 'charts#users_per_day'
  #get 'charts/enrollments_per_day', to: 'charts#enrollments_per_day'
  #get 'charts/popular_courses', to: 'charts#popular_courses'
  #get 'charts/money_makers', to: 'charts#money_makers'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :course, counter_cache: true
  belongs_to :user, counter_cache: true

  #Ensures no enrollment can exist without the presence of a course or user.
  validates :user, :course, presence: true
  

  #Effectively forces that if one exists, the other MUST exist.
  validates_presence_of :rating, if: :review?
  validates_presence_of :review, if: :rating?


  validates_uniqueness_of :user_id, scope: :course_id #user cant be subscribed to same course twice
  #User cannot be enrolled  twice, course cannot have the same ID twice. Secured on both ends
  validates_uniqueness_of :course_id, scope: :user_id #user cant be subscribed to same course twice

  validate :cant_subscribe_to_own_course # user cannot subscribe if course.user == current_user.

  scope :pending_review, -> {where(rating: [0, nil, ""], review: [0, nil, ""])}
  scope :reviewed, -> {where.not(review: [0, nil, ""])}
  scope :latest_reviews, -> {order(rating: :desc, created_at: :desc).limit(3)}


  extend FriendlyId
  #We lack an otherwise effective string, so we use the to_s method below, which will provide a generated string
    friendly_id :to_s, use: :slugged

  def to_s
    user.to_s + " " +  course.to_s
  end

  after_save do
    unless rating.nil? || rating.zero?
      course.update_rating
    end
  end

  after_destroy do
    course.update_rating
  end


  protected

  def cant_subscribe_to_own_course
    # If a new enrollment is being created
    if self.new_record?
      #If said enrollment's user_id parameter is the same as the owner user id of the course
      if self.user_id.present?
        if user_id == course.user_id
          #Generate error
          errors.add(:base, "You cannot subscribe to your own course")
        end
      end
    end
  end


end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: %i[ show edit update destroy ]
  before_action :set_course, only: [:new, :create]
  # GET /enrollments or /enrollments.json
  def index
    #@enrollments = Enrollment.all
    #These custom paths for ransack are passed, depending on what ACTION is calling the view.
    #In Index, itll grab the general, but for my_students, it recognizes the path for that view must be that specific one.
    #It's genius
    @ransack_path = enrollments_path
    @q = Enrollment.ransack(params[:q])
    @pagy, @enrollments = pagy(@q.result.includes(:user), items: 5)
    

    authorize @enrollments
  end

  # GET /enrollments/1 or /enrollments/1.json
  def my_students
    @ransack_path = my_students_enrollments_path
    @q = Enrollment.joins(:course).where(courses: {user: current_user}).ransack(params[:q])
    @pagy, @enrollments = pagy(@q.result.includes(:user), items: 5)
    render 'index'
  end


  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
    authorize @enrollment
  end

  # POST /enrollments or /enrollments.json
  def create
    if @course.price > 0
      flash[:alert] = "You cannot access paid courses yet"
      redirect_to new_course_enrollment_path(@course)
    else
      #if price is more than zero
      #current_user functions as passing a user, which is why I can summon this method
      @enrollment = current_user.buy_course(@course)
      redirect_to course_path(@course), notice: "You are enrolled"
    end

    #Old method of Enrollment
    # @enrollment = Enrollment.new(enrollment_params)
    # @enrollment.price = @enrollment.course.price

    # respond_to do |format|
    #   if @enrollment.save
    #     format.html { redirect_to @enrollment, notice: "Enrollment was successfully created." }
    #     format.json { render :show, status: :created, location: @enrollment }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @enrollment.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /enrollments/1 or /enrollments/1.json
  def update
    authorize @enrollment
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: "Enrollment was successfully updated." }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1 or /enrollments/1.json
  def destroy
    authorize @enrollment
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: "Enrollment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enrollment_params
      params.require(:enrollment).permit(:rating, :review)
    end

    def set_course
      @course = Course.friendly.find(params[:course_id])
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper

end

app/views/enrollments/_enrollment.html.haml
.card
	.card-header
		.fa.fa-user
		= link_to enrollment.user.username, user_path(enrollment.user)
		.fa.fa-clock
		= time_ago_in_words(enrollment.updated_at)
		.fa.fa-graduation-cap
		= link_to enrollment.course, course_path(enrollment.course)
	.card-body
		.row
			.fa.fa-comment
			%small= enrollment.review
		.row
			%b= enrollment.rating
			.text-warning.fa.fa-star
	-if current_user
		.card-footer
			- if policy(enrollment).edit?
				.row
					=link_to "Edit Review", edit_enrollment_path(enrollment), class: 'btn btn-sm btn-warning' 
				%p
				.row
					=link_to "Delete Review", enrollment, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' 

app/views/enrollments/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@enrollment) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :rating, collection: 1..5, as: :radio_buttons
    = f.input :review

  .form-actions
    = f.button :submit

app/views/enrollments/edit.html.haml
- content_for :title do 
  Coursego
  \|
  Editing
  = @enrollment.to_s


%h3 Editing enrollment

.card
  .card-header
    %h3 
      .text-warning.fa.fa-star
      Add a Review
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Show Review', @enrollment
    \|
    = link_to 'Back To Course', course_path(@enrollment.course)

app/views/enrollments/index.html.haml
- content_for :title do 
  Coursego
  \|
  = action_name.humanize
  Enrollments


%h3
  = action_name.humanize
  .badge.badge-info
    =@enrollments.count
%p

!= pagy_bootstrap_nav(@pagy)

%p

= search_form_for @q, url: @ransack_path do |f|
  = f.search_field :review_cont, placeholder: 'review'
  = f.search_field :rating_eq, placeholder: 'rating'
  = f.search_field :user_email_cont, placeholder: 'user'
  = f.search_field :course_title_cont, placeholder: 'course'
  = f.search_field :course_price_eq, placeholder: 'price'
  = f.submit
%p
= link_to 'Refresh', @ransack_path
%br



%h1 Listing enrollments

.table-responsive
  %table.table.table-bordered.table-striped.table-sm
    %thead
      %tr
        %th ID
        %th
          = sort_link(@q, :user_email)
          /.fa.fa-user
          /User
        %th 
          /.fa.fa-clock
          = sort_link(@q, :created_at)
          
        %th
          /.fa.fa-graduation-cap
          = sort_link(@q, :course_title) 
          /Course
        %th 
          /.fa.fa-dollar-sign  
          = sort_link(@q, :price) 
          /Price
        %th 
          = sort_link(@q, :updated_at) 
          /.text-warning.fa.fa-clock
          /Reviewed On
        %th 
          = sort_link(@q, :rating) 
          /.text-warning.fa.fa-star
          /Rating
        %th 
          .text-warning.fa.fa-comment
          Review
        %th Progress
        %th See Review
        %th Add Review
        %th Remove Student

    %tbody
      - @enrollments.each do |enrollment|
        %tr
          %td= enrollment.id
          %td= link_to enrollment.user, user_path(enrollment.user)
          %td= enrollment.created_at.strftime("%d/%b/%Y,%H:%M")
          %td= link_to enrollment.course, course_path(enrollment.course)
          %td= number_to_currency(enrollment.price)
          %td
            -if enrollment.rating.present?
              = enrollment.updated_at.strftime("%d/%b/%Y,%H:%M")
          %td= enrollment.rating
          %td= enrollment.review
          %td= number_to_percentage(enrollment.course.progress(enrollment.user), precision: 0)
          %td= link_to 'See Review', enrollment
          %td
            - if policy(enrollment).edit?
              = link_to 'Add Review', edit_enrollment_path(enrollment)
          %td
            -if policy(enrollment).destroy?
              = link_to 'Delete Enrollment', enrollment, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Enrollment', new_enrollment_path

app/views/enrollments/new.html.haml
- content_for :title do 
  Coursego
  \|
  New Enrollment


%h3 New enrollment
.card
  .card-header
    %h3 
      .fa.fa-graduation-cap
      = link_to @course.title, course_path(@course)
      %hr
        .fa.fa-lock-open
        Buy Course
  .card-body
    = form_tag course_enrollments_path(@course) do
      = submit_tag "Pay #{number_to_currency(@course.price)}", class: "btn btn-md btn-success"

  .card-footer
    = link_to 'Back', enrollments_path

app/views/enrollments/show.html.haml
= render 'enrollments/enrollment', enrollment: @enrollment