config/routes.rb
Rails.application.routes.draw do
  resources :enrollments do 
    get :my_students, on: :collection
  end
  devise_for :users
  resources :users
  resources :courses do
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    #I believe member here stands for current course
    #The member do lets me nest things within the show action. - How do I know its specifically show? What made it show.
    member do
      #This will add two new accounts in our routes.
      get :analytics
      patch :approve
      patch :unapprove
    end
    #Enrollments is above too, but im basically subclassing routes for enrollments methods new + create
    #beneath courses, so enrollments_new_path becomes courses_enrollments_new_path (a fictious example)
      resources :enrollments, only: [:new, :create]
      resources :lessons

  end
  root'home#index'
  get 'activity', to: 'home#activity'
  get 'analytics', to: 'home#analytics'

  namespace :charts do     
    get 'money_makers'
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'popular_courses'
  end
  #Compare above and below, since it seems to auto direct to the right method immediately.
  #get 'charts/users_per_day', to: 'charts#users_per_day'
  #get 'charts/enrollments_per_day', to: 'charts#enrollments_per_day'
  #get 'charts/popular_courses', to: 'charts#popular_courses'
  #get 'charts/money_makers', to: 'charts#money_makers'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course, counter_cache: true
  validates :title, :content, :course, presence: true

  has_many :user_lessons, dependent: :destroy

  has_rich_text :content

  extend FriendlyId
  friendly_id :title, use: :slugged
  
    include PublicActivity::Model
    # We track the owner by assigning it based on the current user
    tracked owner: Proc.new{ |controller, model| controller.current_user}

    #This converts the title to a proper string from the ActiveRecord piece it currently is.
    #This is a new note.
    def to_s
      title
    end

    def viewed(user)
      self.user_lessons.where(user: user).present?
      #Alternative below
      # self.user_lessons.where(user_id: [user_id], lesson_id: [self.id]).empty?
    end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[ show edit update destroy ]


  # GET /lessons or /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1 or /lessons/1.json
  def show
    authorize @lesson
    # view_lesson beingthe method which verifies things first. Called from, presumably, user.rb (not lesson.rb)
    current_user.view_lesson(@lesson)
    #Course works because in private set_lesson we already have it set, as part of set_lesson. This means the below code
    #will function as expected
     @lessons = @course.lessons
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
    @course = Course.friendly.find(params[:course_id])
  end

  # GET /lessons/1/edit
  def edit
    authorize @lesson
  end

  # POST /lessons or /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)
    @course = Course.friendly.find(params[:course_id])
    @lesson.course_id = @course.id
    authorize @lesson

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to course_lesson_path(@course, @lesson), notice: "Lesson was successfully created." }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1 or /lessons/1.json
  def update
    authorize @lesson
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to course_lesson_path(@course, @lesson), notice: "Lesson was successfully updated." }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1 or /lessons/1.json
  def destroy
    authorize @lesson
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to course_path(@course), notice: "Lesson was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @course = Course.friendly.find(params[:course_id])
      @lesson = Lesson.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lesson_params
      params.require(:lesson).permit(:title, :content)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.haml
-# frozen_string_literal: true
= simple_form_for([@course, @lesson]) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    /= f.input :content
    = f.label :content
    = f.rich_text_area :content
    %small= f.error :content, class: "text-danger"
    /= f.association :course
    -# = this piece of code lets me fill in the association provided there is a parameter at all, and is kept hidden.
    -# = good thing to note for the future
    /= f.input :course_id, input_html: {value: @lesson.course_id || params[:course_id]}, as: :hidden
    %p
    
  .form-actions
    = f.button :submit

app/views/lessons/_lesson.html.haml
.card
  .card-header
    - if lesson.viewed(current_user) == true
      .text-success.far.fa-check-square
      VIEWED
    - else
      NOT VIEWED
      .text-danger.far.fa-check-square
    = link_to lesson.title, course_lesson_path(@course, lesson)
  - if policy(lesson).show? 
    .card-body
      = lesson.content
  - if policy(lesson).edit?  
    .card-footer
      = link_to 'Edit', edit_course_lesson_path(@course, lesson), class: 'btn btn-sm btn-warning' 
      = link_to 'Destroy', [@course, lesson], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' 
%p

app/views/lessons/_lesson_preview.html.haml
- if lesson.viewed(current_user) == true
	.text-success.far.fa-check-square
- else
	.text-danger.far.fa-check-square
= link_to lesson.title, course_lesson_path(@course, lesson)
.float-right
	- if policy(lesson).edit?  
		= link_to 'Edit', edit_course_lesson_path(@course, lesson), class: 'btn btn-sm btn-warning' 
		= link_to 'Destroy', [@course, lesson], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' 

app/views/lessons/edit.html.haml
- content_for :title do 
	Coursego
	\|
	= @lesson.course.title
	\|
	= @lesson.title





= link_to 'Courses', courses_path
\/
= link_to @lesson.course.title ,course_path(@lesson.course)
\/
= link_to @lesson.title ,course_lesson_path(@course, @lesson)
\/
Edit

.card
	.card-header
		%h3
			.far.fa-check-square
			Editing lesson
	.card-body
		= render 'form'
	.card-footer
		= link_to 'Show', course_lesson_path(@course, @lesson)
		\|
		= link_to 'Back', course_path(@lesson.course)

app/views/lessons/index.html.haml
%h1 Listing lessons

%table
  %thead
    %tr
      %th Title
      %th Content
      %th Course
      %th
      %th
      %th

  %tbody
    - @lessons.each do |lesson|
      %tr
        %td= lesson.title
        %td= lesson.content
        %td= lesson.course
        %td= link_to 'Show', lesson
        %td= link_to 'Edit', edit_lesson_path(lesson)
        %td= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Lesson', new_lesson_path

app/views/lessons/new.html.haml
- content_for :title do 
	Coursego
	\|
	= @course.title
	\|
	New Lesson




= link_to 'Courses', courses_path
\/
= link_to @course.title ,course_path(@course)
\/
New Lesson


.card
	.card-header
		%h3
			.far.fa-check-square
			New lesson
	.card-body
		= render 'form'
	.card-footer
		= link_to 'Back', course_path(@course)
-# Below is a solid breadcrumbs style to emulate

/ = link_to 'Courses', courses_path
/ \/
/ = link_to @course.title ,course_path(@course)
/ \/
/ New Lesson





/= link_to 'Back', course_path(@course)

app/views/lessons/show.html.haml
- content_for :title do 
  Coursego
  |
  Course
  = @lesson.course.title
  |
  Lesson
  = @lesson.title



%p#notice=notice

-# Below is a solid breadcrumbs style to emulate

= link_to 'Courses', courses_path
|
= link_to course_path(@lesson.course) do
  .fa.fa-graduation-cap
  = @lesson.course.title  
|
= link_to course_lesson_path(@course, @lesson) do
  .fa.fa-graduation-cap
  = @lesson.title  

%p

/= @lesson.user_lessons.where(user: current_user).first.impressions

.row
  .col-lg-8
    = render 'lessons/lesson', lesson: @lesson
    %p
  .col-lg-4
    %ul.list-group
      %li.list-group-item
        = link_to course_path(@lesson.course) do
          .fa.fa-graduation-cap
          = @lesson.course.title 
        %p
        .row
        .fa.fa-spinner
        =number_to_percentage(@course.progress(current_user), precision: 0) 
      - @lessons.each do |lesson|
        /If the lesson is present, meaning the @lesson we passed in the render above.
        /and Lesson (do variable) is equal to the one passed above, use success LGIS
        - if @lesson.present? && lesson == @lesson
          %li.list-group-item.bg.list-group-item-success
            = render 'lessons/lesson_preview', lesson: lesson
        - else
          %li.list-group-item.bg
            = render 'lessons/lesson_preview', lesson: lesson